import { useMemo } from "react";
import type { WorkshopModalsProps } from "./workshopModals.types";
import type { UseWorkshopModalsPropsArgs } from "./useWorkshopModalsProps.types";

export function useWorkshopModalsProps(args: UseWorkshopModalsPropsArgs): WorkshopModalsProps {
  const {
    projectId,
    isLegacyProject,
    onOpenSettings,
    workshopStagesList,
    activeStageId,
    createWorkshopStage,
    fetchProject,
    showStageModal,
    setShowStageModal,
    showHelpModal,
    setShowHelpModal,
    flowOrderModalOpen,
    setFlowOrderModalOpen,
    dbgaRestoreOpen,
    setDbgaRestoreOpen,
    modelsUnavailableModalOpen,
    setModelsUnavailableModalOpen,
    showAuditModal,
    setShowAuditModal,
    liveMetrics,
    documentCompleteness,
    consistencyScore,
    precisionBreakdown,
    mddReadinessHints,
    traceabilityHints,
    crossDocumentGaps,
    auditTrail,
    effectiveMddTrimmed,
    canRegenerateMddSection,
    mddSectionRegenDisabledReason,
    handleRegenerateMddSectionFromQuality,
    reapplyMddFormat,
    clearMddConfirmOpen,
    setClearMddConfirmOpen,
    handleClearMddCompletely,
    mddPatternsWizardOpen,
    setMddPatternsWizardOpen,
    mddPatternsWizardMode,
    patternsWizardPreselected,
    patternsWizardAnalyzing,
    patternsAnalyzeRationale,
    loading,
    loadingReason,
    mddReviewing,
    handleMddPatternsWizardConfirm,
    mddRegenerateDialogOpen,
    setMddRegenerateDialogOpen,
    generationStatus,
    mddRegenerateInitialMode,
    handleMddRegenerateFull,
    handleMddRegenerateSync,
    aemGenerateDialogOpen,
    setAemGenerateDialogOpen,
    handleGenerateAem,
  } = args;

  return useMemo((): WorkshopModalsProps => ({
      projectId,
      isLegacyProject,
      onOpenSettings,
      workshopStagesList,
      activeStageId,
      createWorkshopStage,
      fetchProject,
      showStageModal,
      setShowStageModal,
      showHelpModal,
      setShowHelpModal,
      flowOrderModalOpen,
      setFlowOrderModalOpen,
      dbgaRestoreOpen,
      setDbgaRestoreOpen,
      modelsUnavailableModalOpen,
      setModelsUnavailableModalOpen,
      audit: {
        open: showAuditModal,
        onClose: () => setShowAuditModal(false),
        liveMetrics,
        documentCompleteness,
        consistencyScore,
        precisionBreakdown,
        mddReadinessHints,
        traceabilityHints,
        crossDocumentGaps,
        auditTrail,
        projectId,
        activeStageId,
        effectiveMddTrimmed,
        canRegenerateMddSection,
        mddSectionRegenDisabledReason,
        onRegenerateMddSection: (section) => void handleRegenerateMddSectionFromQuality(section),
        onReapplyMddFormat: () => void reapplyMddFormat(),
      },
      clearMddConfirmOpen,
      setClearMddConfirmOpen,
      onClearMddConfirm: async () => {
        const ok = await handleClearMddCompletely();
        if (ok) setClearMddConfirmOpen(false);
      },
      mddPatternsWizardOpen,
      setMddPatternsWizardOpen,
      mddPatternsWizardMode,
      effectiveMddTrimmed,
      patternsWizardPreselected,
      patternsWizardAnalyzing,
      patternsAnalyzeRationale,
      patternsWizardLoading:
        (loading && loadingReason === "mdd") ||
        (mddPatternsWizardMode === "edit" && mddReviewing),
      onMddPatternsWizardConfirm: handleMddPatternsWizardConfirm,
      mddRegenerateDialogOpen,
      setMddRegenerateDialogOpen,
      mddUpstreamSync: generationStatus?.mddUpstreamSync,
      mddRegenerateInitialMode,
      mddRegenerateLoading: loading && loadingReason === "mdd",
      onMddRegenerateFull: handleMddRegenerateFull,
      onMddRegenerateSync: handleMddRegenerateSync,
      aemGenerateDialogOpen,
      setAemGenerateDialogOpen,
      aemGenerateLoading: loading && loadingReason === "aem",
      onGenerateAem: handleGenerateAem,
    }),
    [
      projectId,
      isLegacyProject,
      onOpenSettings,
      workshopStagesList,
      activeStageId,
      createWorkshopStage,
      fetchProject,
      showStageModal,
      showHelpModal,
      flowOrderModalOpen,
      dbgaRestoreOpen,
      modelsUnavailableModalOpen,
      showAuditModal,
      liveMetrics,
      documentCompleteness,
      consistencyScore,
      precisionBreakdown,
      mddReadinessHints,
      traceabilityHints,
      crossDocumentGaps,
      auditTrail,
      effectiveMddTrimmed,
      canRegenerateMddSection,
      mddSectionRegenDisabledReason,
      handleRegenerateMddSectionFromQuality,
      reapplyMddFormat,
      clearMddConfirmOpen,
      handleClearMddCompletely,
      mddPatternsWizardOpen,
      mddPatternsWizardMode,
      patternsWizardPreselected,
      patternsWizardAnalyzing,
      patternsAnalyzeRationale,
      loading,
      loadingReason,
      mddReviewing,
      handleMddPatternsWizardConfirm,
      mddRegenerateDialogOpen,
      generationStatus?.mddUpstreamSync,
      mddRegenerateInitialMode,
      handleMddRegenerateFull,
      handleMddRegenerateSync,
      aemGenerateDialogOpen,
      handleGenerateAem,
    ],
  );
}
