import { useMemo } from "react";
import { ClipboardPaste, MessageSquare } from "lucide-react";
import { resolveWorkshopDocEditToolbarToggle, type WorkshopComplexityTier } from "@/utils/workshopDocToolbar";
import type {
  WorkshopDocEditToolbarToggle,
  WorkshopDocToolbarProps,
} from "./workshopDocToolbar.types";
import type { UseWorkshopDocToolbarPropsArgs } from "./useWorkshopDocToolbarProps.types";

export function useWorkshopDocToolbarProps(
  args: UseWorkshopDocToolbarPropsArgs,
): {
  workshopDocToolbarProps: WorkshopDocToolbarProps;
  phase0EntryModeToolbarToggle: WorkshopDocEditToolbarToggle | null;
} {
  const {
    centralPanel,
    effectiveComplexityForTabs,
    isLegacyProject,
    benchmarkPhaseTab,
    phase0IsEmpty,
    phase0EntryMode,
    setPhase0EntryMode,
    mddViewMode,
    mddInicialViewMode,
    specViewMode,
    architectureViewMode,
    useCasesViewMode,
    userStoriesViewMode,
    uxUiGuideViewMode,
    aemViewMode,
    blueprintViewMode,
    apiContractsViewMode,
    logicFlowsViewMode,
    brdDocViewMode,
    infraViewMode,
    agentGovernanceViewMode,
    tasksViewMode,
    blueprintContent,
    tasksContent,
    hasAgentGovernance,
    apiContractsContent,
    architectureContent,
    useCasesContent,
    userStoriesContent,
    logicFlowsContent,
    infraContent,
    activeLegacyState,
    mddInicialLocalContent,
    activeStageId,
    specContent,
    aemContent,
    uxUiGuideContent,
    activeStageShortTermContext,
    loading,
    projectId,
    loadingReason,
    effectiveMddTrimmed,
    mddReviewing,
    apiBlueprintDmBlocked,
    apiBlueprintBlockedHint,
    mddInicialSaving,
    brdWorkshopDirty,
    brdTobePersistBusy,
    canGenerateAem,
    tasksPrerequisites,
    agentGovernanceGenerating,
    uxGenerating,
    uxGenProgress,
    benchmarkViewMode,
    phase0SummaryViewMode,
    isLgLayout,
    lgWorkshopChatCollapsed,
    toggleDocViewMode,
    setFlowOrderModalOpen,
    setClarifySpecDialogOpen,
    setDbgaRestoreOpen,
    handlePrintDocument,
    setBenchmarkViewMode,
    setPhase0SummaryViewMode,
    generateArchitecture,
    generateUseCases,
    generateUserStories,
    generateBlueprint,
    generateApiContracts,
    generateLogicFlows,
    generateInfra,
    handleRegenerateLegacyCodebaseDoc,
    setMddInicialSaving,
    legacyUpdateCodebaseDoc,
    persistBrdWorkshopDraft,
    generateSpec,
    setAemGenerateDialogOpen,
    generateTasks,
    convergeTasks,
    setError,
    tasksToIssues,
    generateAgentGovernance,
    repairUxGuide,
    generateUxGuideSequential,
    handleSetLgWorkshopChatCollapsed,
  } = args;

  const phase0EntryModeToolbarToggle = useMemo(() => {
    if (!phase0IsEmpty) return null;
    return {
      Icon: phase0EntryMode === "interview" ? ClipboardPaste : MessageSquare,
      tooltip: phase0EntryMode === "interview" ? "Pegar Paso 0" : "Entrevista con IA",
      onClick: () => setPhase0EntryMode((m) => (m === "interview" ? "paste" : "interview")),
    };
  }, [phase0IsEmpty, phase0EntryMode]);

  /** Preview/source (or design) toggle — header toolbar on desktop; not in the bubble menu. */
  const docEditToolbarToggle = useMemo(
    () =>
      resolveWorkshopDocEditToolbarToggle({
        centralPanel,
        viewModes: {
          mddViewMode,
          mddInicialViewMode,
          specViewMode,
          architectureViewMode,
          useCasesViewMode,
          userStoriesViewMode,
          uxUiGuideViewMode,
          aemViewMode,
          blueprintViewMode,
          apiContractsViewMode,
          logicFlowsViewMode,
          brdDocViewMode,
          infraViewMode,
          agentGovernanceViewMode,
          tasksViewMode,
        },
        content: {
          blueprintContent,
          tasksContent,
          hasAgentGovernance,
          apiContractsContent,
          architectureContent,
          useCasesContent,
          userStoriesContent,
          logicFlowsContent,
          infraContent,
          activeLegacyState,
          mddInicialLocalContent,
          activeStageId,
        },
        hasAgentGovernance,
        benchmarkPhaseTab,
        benchmarkViewMode,
        phase0SummaryViewMode,
        phase0EntryModeToolbarToggle,
        toggleDocViewMode,
        setBenchmarkViewMode,
        setPhase0SummaryViewMode,
      }),
    [
      centralPanel,
      mddViewMode,
      mddInicialViewMode,
      specViewMode,
      architectureViewMode,
      useCasesViewMode,
      userStoriesViewMode,
      uxUiGuideViewMode,
      aemViewMode,
      blueprintViewMode,
      apiContractsViewMode,
      logicFlowsViewMode,
      brdDocViewMode,
      infraViewMode,
      agentGovernanceViewMode,
      tasksViewMode,
      hasAgentGovernance,
      benchmarkPhaseTab,
      benchmarkViewMode,
      phase0SummaryViewMode,
      blueprintContent,
      tasksContent,
      apiContractsContent,
      architectureContent,
      useCasesContent,
      userStoriesContent,
      logicFlowsContent,
      infraContent,
      activeLegacyState,
      mddInicialLocalContent,
      activeStageId,
      toggleDocViewMode,
      phase0EntryModeToolbarToggle,
    ],
  );

  const workshopDocToolbarProps = useMemo((): WorkshopDocToolbarProps => ({
    centralPanel,
    effectiveComplexityForTabs: effectiveComplexityForTabs as WorkshopComplexityTier,
    isLegacyProject,
    benchmarkPhaseTab,
    docEditToolbarToggle,
    viewModes: {
      mddViewMode,
      mddInicialViewMode,
      specViewMode,
      architectureViewMode,
      useCasesViewMode,
      userStoriesViewMode,
      uxUiGuideViewMode,
      aemViewMode,
      blueprintViewMode,
      apiContractsViewMode,
      logicFlowsViewMode,
      brdDocViewMode,
      infraViewMode,
      agentGovernanceViewMode,
      tasksViewMode,
    },
    content: {
      blueprintContent,
      tasksContent,
      hasAgentGovernance,
      apiContractsContent,
      architectureContent,
      useCasesContent,
      userStoriesContent,
      logicFlowsContent,
      infraContent,
      activeLegacyState,
      mddInicialLocalContent,
      activeStageId,
      specContent,
      aemContent,
      uxUiGuideContent,
      activeStageShortTermContext,
    },
    ui: {
      loading,
      projectId,
      loadingReason,
      effectiveMddTrimmed,
      mddReviewing,
      apiBlueprintDmBlocked,
      apiBlueprintBlockedHint,
      mddInicialViewMode,
      mddInicialSaving,
      brdDocViewMode,
      brdWorkshopDirty,
      brdTobePersistBusy,
      canGenerateAem,
      tasksPrerequisites,
      agentGovernanceGenerating,
      uxGenerating,
      uxGenProgress,
      benchmarkViewMode,
      phase0SummaryViewMode,
      phase0EntryModeToolbarToggle,
      isLgLayout,
      lgWorkshopChatCollapsed,
    },
    actions: {
      toggleDocViewMode,
      setFlowOrderModalOpen,
      setClarifySpecDialogOpen,
      setDbgaRestoreOpen,
      handlePrintDocument,
      setBenchmarkViewMode,
      setPhase0SummaryViewMode,
      generateArchitecture,
      generateUseCases,
      generateUserStories,
      generateBlueprint,
      generateApiContracts,
      generateLogicFlows,
      generateInfra,
      handleRegenerateLegacyCodebaseDoc,
      setMddInicialSaving,
      legacyUpdateCodebaseDoc,
      persistBrdWorkshopDraft,
      generateSpec,
      setAemGenerateDialogOpen,
      generateTasks,
      convergeTasks,
      setError,
      tasksToIssues,
      generateAgentGovernance,
      repairUxGuide,
      generateUxGuideSequential,
      handleSetLgWorkshopChatCollapsed,
    },
  }), [
    centralPanel,
    effectiveComplexityForTabs,
    isLegacyProject,
    benchmarkPhaseTab,
    docEditToolbarToggle,
    mddViewMode,
    mddInicialViewMode,
    specViewMode,
    architectureViewMode,
    useCasesViewMode,
    userStoriesViewMode,
    uxUiGuideViewMode,
    aemViewMode,
    blueprintViewMode,
    apiContractsViewMode,
    logicFlowsViewMode,
    brdDocViewMode,
    infraViewMode,
    agentGovernanceViewMode,
    tasksViewMode,
    blueprintContent,
    tasksContent,
    hasAgentGovernance,
    apiContractsContent,
    architectureContent,
    useCasesContent,
    userStoriesContent,
    logicFlowsContent,
    infraContent,
    activeLegacyState,
    mddInicialLocalContent,
    activeStageId,
    specContent,
    aemContent,
    uxUiGuideContent,
    activeStageShortTermContext,
    loading,
    projectId,
    loadingReason,
    effectiveMddTrimmed,
    mddReviewing,
    apiBlueprintDmBlocked,
    apiBlueprintBlockedHint,
    mddInicialViewMode,
    mddInicialSaving,
    brdDocViewMode,
    brdWorkshopDirty,
    brdTobePersistBusy,
    canGenerateAem,
    tasksPrerequisites,
    agentGovernanceGenerating,
    uxGenerating,
    uxGenProgress,
    benchmarkViewMode,
    phase0SummaryViewMode,
    phase0EntryModeToolbarToggle,
    isLgLayout,
    lgWorkshopChatCollapsed,
    toggleDocViewMode,
    handlePrintDocument,
    handleRegenerateLegacyCodebaseDoc,
    persistBrdWorkshopDraft,
    generateArchitecture,
    generateUseCases,
    generateUserStories,
    generateBlueprint,
    generateApiContracts,
    generateLogicFlows,
    generateInfra,
    generateSpec,
    generateTasks,
    convergeTasks,
    tasksToIssues,
    generateAgentGovernance,
    repairUxGuide,
    generateUxGuideSequential,
    handleSetLgWorkshopChatCollapsed,
    setError,
    legacyUpdateCodebaseDoc,
  ]);



  return { workshopDocToolbarProps, phase0EntryModeToolbarToggle };
}
