import { useCallback, useMemo } from "react";
import { useWorkshopStore } from "@/store/workshopStore";
import type { WorkshopDocPanelContentProps } from "./workshopDocPanelContent.types";
import type { UseWorkshopDocPanelPropsArgs } from "./useWorkshopDocPanelProps.types";

export function useWorkshopDocPanelProps(
  args: UseWorkshopDocPanelPropsArgs,
): WorkshopDocPanelContentProps {
  const {
    centralPanel,
    projectId,
    projectName,
    mergeAudit,
    project,
    activeWorkshopStage,
    effectiveMddTrimmed,
    loading,
    loadingReason,
    mddReviewing,
    canGenerateFromCodebase,
    activeStageId,
    deliverablesReadOnly,
    tasksPrerequisites,
    apiBlueprintDmBlocked,
    apiBlueprintBlockedHint,
    docTs,
    buildDocClarification,
    legacyGenerateFromCodebaseDoc,
    architectureContent,
    setArchitectureContent,
    persistArchitectureContent,
    architectureDirty,
    architectureViewMode,
    generateArchitecture,
    handleArchitectureBlur,
    useCasesContent,
    setUseCasesContent,
    persistUseCasesContent,
    useCasesDirty,
    useCasesViewMode,
    generateUseCases,
    handleUseCasesBlur,
    userStoriesContent,
    setUserStoriesContent,
    persistUserStoriesContent,
    userStoriesDirty,
    userStoriesViewMode,
    generateUserStories,
    handleUserStoriesBlur,
    blueprintContent,
    setBlueprintContent,
    persistBlueprintContent,
    blueprintDirty,
    blueprintViewMode,
    generateBlueprint,
    handleBlueprintBlur,
    tasksContent,
    setTasksContent,
    persistTasksContent,
    tasksDirty,
    tasksViewMode,
    generateTasks,
    handleTasksBlur,
    apiContractsContent,
    setApiContractsContent,
    persistApiContractsContent,
    apiContractsDirty,
    apiContractsViewMode,
    generateApiContracts,
    handleApiContractsBlur,
    logicFlowsContent,
    setLogicFlowsContent,
    persistLogicFlowsContent,
    logicFlowsDirty,
    logicFlowsViewMode,
    generateLogicFlows,
    handleLogicFlowsBlur,
    infraContent,
    setInfraContent,
    persistInfraContent,
    infraDirty,
    infraViewMode,
    generateInfra,
    handleInfraBlur,
    activeLegacyState,
    isStage1Legacy,
    error,
    legacyStepIndex,
    mddInicialLocalContent,
    mddInicialViewMode,
    mddInicialCopyOk,
    legacyMcpDebugTrace,
    legacyDescriptionInput,
    legacyAnswersInput,
    legacyHandoffGatePending,
    legacyHandoffGateBlocked,
    legacyChangeGateBlocked,
    legacyGenerateBlocked,
    handoffGateStrict,
    legacyAnalyzeDone,
    workshopStagesList,
    copyMddInicialMarkdown,
    setMddInicialLocalContent,
    setLegacyDescriptionInput,
    setLegacyAnswersInput,
    handleHandoffGateStrictChange,
    resolveLegacyAnswerValue,
    setCentralPanel,
    fetchProject,
    legacyUpdateCodebaseDoc,
    legacySuggestBrdFromCodebaseDoc,
    setBrdWorkshopDraft,
    legacyGenerateMdd,
    legacyGenerateDeliverables,
    legacyGenerateCodebaseDoc,
    legacyStart,
    legacyAnswer,
    dbgaContent,
    specContent,
    fase0Content,
    phase0IsEmpty,
    phase0EntryMode,
    benchmarkPhaseTab,
    benchmarkViewMode,
    phase0SummaryViewMode,
    benchmarkMarkdown,
    benchmarkNeedsRegenerate,
    phase0SummaryContent,
    lastBenchmarkIdea,
    setBenchmarkPhaseTab,
    handlePhase0Complete,
    setDbgaRestoreOpen,
    setDbgaContent,
    setPhase0SummaryContent,
    handleBenchmarkBlur,
    handlePhase0SummaryBlur,
    suggestBrdFromDbga,
    clearDbgaContent,
    clearPhase0SummaryContent,
    phase0DeepResearch,
    mddContent,
    mddViewMode,
    mddDirty,
    mddPersisting,
    mddReapplyingFormat,
    mddJustGeneratedFromBenchmark,
    notice,
    isLegacyProject,
    legacyMddNeedsCodebaseDoc,
    patternsWizardAnalyzing,
    canGenerate,
    cascadeRunning,
    cascadeCompleted,
    cascadeTotal,
    cascadePostPassRunning,
    isGenerationGateBlocked,
    clearMddJustGeneratedFromBenchmark,
    requestGenerateMdd,
    reapplyMddFormat,
    openSuggestMddPatterns,
    openEditMddPatterns,
    setClearMddConfirmOpen,
    handleGenerateDeliverables,
    setMddContent,
    revertMddContent,
    persistAndReviewMdd,
    aemContent,
    uiScreensContent,
    brdWorkshopDraft,
    brdDocViewMode,
    specViewMode,
    aemViewMode,
    specDirty,
    aemDirty,
    brdWorkshopDirty,
    brdTobePersistBusy,
    canGenerateAem,
    clarifySpecDialogOpen,
    stageDeliverableView,
    setSpecContent,
    setAemContent,
    setClarifySpecDialogOpen,
    persistSpecContent,
    persistAemContent,
    persistBrdWorkshopDraft,
    generateSpec,
    setAemGenerateDialogOpen,
    syncUiScreens,
    handleSpecBlur,
    handleAemBlur,
    agentGovernanceContent,
    agentGovernanceViewMode,
    agentGovernanceExportScaffold,
    agentGovernanceExportLoading,
    agentGovernanceGenerating,
    hasAgentGovernance,
    documentationGapsRefreshNonce,
    generateAgentGovernance,
    uxUiGuideContent,
    uxUiGuideViewMode,
    uxGenerating,
    setUxUiGuideContent,
    persistUxUiGuideContent,
    generateUxGuideSequential,
    handleDesignRefChange,
    handleUxUiGuideBlur,
    adrs,
    pluginArtifactTypes,
    fetchAdrs,
  } = args;

  const handleMddAuditUpdated = useCallback(async () => {
    const store = useWorkshopStore.getState();
    await store.fetchProject(projectId);
    await store.fetchEstimation(projectId);
  }, [projectId]);

  const uxUiGuideDirty = (uxUiGuideContent ?? "") !== (project?.uxUiGuideContent ?? "");

  const workshopStandardDocPanelsProps = useMemo(
    (): import("./workshopStandardDocPanels.types").WorkshopStandardDocPanelsProps => ({
      centralPanel,
      effectiveMddTrimmed,
      loading,
      loadingReason,
      mddReviewing,
      canGenerateFromCodebase,
      activeStageId,
      deliverablesReadOnly,
      tasksPrerequisites,
      apiBlueprintDmBlocked,
      apiBlueprintBlockedHint,
      docTs,
      buildDocClarification,
      onLegacyGenerate: (deliverable) => {
        void legacyGenerateFromCodebaseDoc(
          projectId,
          deliverable,
          activeStageId ?? undefined,
        );
      },
      architecture: {
        content: architectureContent,
        onContentChange: setArchitectureContent,
        onSave: () => void persistArchitectureContent(architectureContent ?? ""),
        isDirty: architectureDirty,
        viewMode: architectureViewMode,
        onGenerate: () => generateArchitecture(projectId),
        onBlur: handleArchitectureBlur,
        timestampField: "architectureContent",
        clarifyField: "architectureContent",
      },
      useCases: {
        content: useCasesContent,
        onContentChange: setUseCasesContent,
        onSave: () => void persistUseCasesContent(useCasesContent ?? ""),
        isDirty: useCasesDirty,
        viewMode: useCasesViewMode,
        onGenerate: () => generateUseCases(projectId),
        onBlur: handleUseCasesBlur,
        timestampField: "useCasesContent",
        clarifyField: "useCasesContent",
      },
      userStories: {
        content: userStoriesContent,
        onContentChange: setUserStoriesContent,
        onSave: () => void persistUserStoriesContent(userStoriesContent ?? ""),
        isDirty: userStoriesDirty,
        viewMode: userStoriesViewMode,
        onGenerate: () => generateUserStories(projectId),
        onBlur: handleUserStoriesBlur,
        timestampField: "userStoriesContent",
        clarifyField: "userStoriesContent",
      },
      blueprint: {
        content: blueprintContent,
        onContentChange: setBlueprintContent,
        onSave: () => void persistBlueprintContent(blueprintContent ?? ""),
        isDirty: blueprintDirty,
        viewMode: blueprintViewMode,
        onGenerate: () => generateBlueprint(projectId),
        onBlur: handleBlueprintBlur,
        timestampField: "blueprintContent",
        clarifyField: "blueprintContent",
      },
      tasks: {
        content: tasksContent,
        onContentChange: setTasksContent,
        onSave: () => void persistTasksContent(tasksContent ?? ""),
        isDirty: tasksDirty,
        viewMode: tasksViewMode,
        onGenerate: () => generateTasks(projectId),
        onBlur: handleTasksBlur,
        timestampField: "tasksContent",
        clarifyField: "tasksContent",
      },
      apiContracts: {
        content: apiContractsContent,
        onContentChange: setApiContractsContent,
        onSave: () => void persistApiContractsContent(apiContractsContent ?? ""),
        isDirty: apiContractsDirty,
        viewMode: apiContractsViewMode,
        onGenerate: () => generateApiContracts(projectId),
        onBlur: handleApiContractsBlur,
        timestampField: "apiContractsContent",
        clarifyField: "apiContractsContent",
      },
      logicFlows: {
        content: logicFlowsContent,
        onContentChange: setLogicFlowsContent,
        onSave: () => void persistLogicFlowsContent(logicFlowsContent ?? ""),
        isDirty: logicFlowsDirty,
        viewMode: logicFlowsViewMode,
        onGenerate: () => generateLogicFlows(projectId),
        onBlur: handleLogicFlowsBlur,
        timestampField: "logicFlowsContent",
        clarifyField: "logicFlowsContent",
      },
      infra: {
        content: infraContent,
        onContentChange: setInfraContent,
        onSave: () => void persistInfraContent(infraContent ?? ""),
        isDirty: infraDirty,
        viewMode: infraViewMode,
        onGenerate: () => generateInfra(projectId),
        onBlur: handleInfraBlur,
        timestampField: "infraContent",
        clarifyField: "infraContent",
      },
    }),
    [
      centralPanel,
      effectiveMddTrimmed,
      loading,
      loadingReason,
      mddReviewing,
      canGenerateFromCodebase,
      activeStageId,
      deliverablesReadOnly,
      tasksPrerequisites,
      apiBlueprintDmBlocked,
      apiBlueprintBlockedHint,
      docTs,
      buildDocClarification,
      legacyGenerateFromCodebaseDoc,
      projectId,
      architectureContent,
      setArchitectureContent,
      persistArchitectureContent,
      architectureDirty,
      architectureViewMode,
      generateArchitecture,
      handleArchitectureBlur,
      useCasesContent,
      setUseCasesContent,
      persistUseCasesContent,
      useCasesDirty,
      useCasesViewMode,
      generateUseCases,
      handleUseCasesBlur,
      userStoriesContent,
      setUserStoriesContent,
      persistUserStoriesContent,
      userStoriesDirty,
      userStoriesViewMode,
      generateUserStories,
      handleUserStoriesBlur,
      blueprintContent,
      setBlueprintContent,
      persistBlueprintContent,
      blueprintDirty,
      blueprintViewMode,
      generateBlueprint,
      handleBlueprintBlur,
      tasksContent,
      setTasksContent,
      persistTasksContent,
      tasksDirty,
      tasksViewMode,
      generateTasks,
      handleTasksBlur,
      apiContractsContent,
      setApiContractsContent,
      persistApiContractsContent,
      apiContractsDirty,
      apiContractsViewMode,
      generateApiContracts,
      handleApiContractsBlur,
      logicFlowsContent,
      setLogicFlowsContent,
      persistLogicFlowsContent,
      logicFlowsDirty,
      logicFlowsViewMode,
      generateLogicFlows,
      handleLogicFlowsBlur,
      infraContent,
      setInfraContent,
      persistInfraContent,
      infraDirty,
      infraViewMode,
      generateInfra,
      handleInfraBlur,
    ],
  );

  const workshopLegacyPanelsProps = useMemo(
    (): import("./workshopLegacyPanels.types").WorkshopLegacyPanelsProps => ({
      centralPanel,
      projectId,
      projectType: project?.projectType,
      projectMddContent: project?.mddContent,
      projectName: project?.name ?? projectName ?? "",
      convergeWebhookUrl: project?.convergeWebhookUrl ?? null,
      canGenerateFromCodebase,
      activeStageId,
      activeLegacyState,
      isStage1Legacy,
      loading,
      loadingReason,
      error,
      legacyStepIndex,
      mddInicialLocalContent,
      mddInicialViewMode,
      mddInicialCopyOk,
      legacyMcpDebugTrace,
      legacyDescriptionInput,
      legacyAnswersInput,
      legacyHandoffGatePending,
      legacyHandoffGateBlocked,
      legacyChangeGateBlocked,
      legacyGenerateBlocked,
      handoffGateStrict,
      legacyAnalyzeDone,
      workshopStagesList,
      activeStageHandoffImportedAt: activeWorkshopStage?.handoffImportedAt ?? null,
      activeStageWorkflowStatus: activeWorkshopStage?.workflowStatus ?? null,
      docTs,
      onCopyMddInicialMarkdown: copyMddInicialMarkdown,
      onMddInicialContentChange: setMddInicialLocalContent,
      onLegacyDescriptionChange: setLegacyDescriptionInput,
      onLegacyAnswersChange: setLegacyAnswersInput,
      onHandoffGateStrictChange: handleHandoffGateStrictChange,
      resolveLegacyAnswerValue,
      onNavigatePanel: setCentralPanel,
      onFetchProject: fetchProject,
      onLegacyUpdateCodebaseDoc: legacyUpdateCodebaseDoc,
      onLegacySuggestBrdFromCodebaseDoc: legacySuggestBrdFromCodebaseDoc,
      onSetBrdWorkshopDraft: setBrdWorkshopDraft,
      onLegacyGenerateMdd: legacyGenerateMdd,
      onLegacyGenerateDeliverables: legacyGenerateDeliverables,
      onLegacyGenerateCodebaseDoc: legacyGenerateCodebaseDoc,
      onLegacyStart: legacyStart,
      onLegacyAnswer: legacyAnswer,
    }),
    [
      centralPanel,
      projectId,
      project?.projectType,
      project?.mddContent,
      project?.name,
      project?.convergeWebhookUrl,
      projectName,
      canGenerateFromCodebase,
      activeStageId,
      activeLegacyState,
      isStage1Legacy,
      loading,
      loadingReason,
      error,
      legacyStepIndex,
      mddInicialLocalContent,
      mddInicialViewMode,
      mddInicialCopyOk,
      legacyMcpDebugTrace,
      legacyDescriptionInput,
      legacyAnswersInput,
      legacyHandoffGatePending,
      legacyHandoffGateBlocked,
      legacyChangeGateBlocked,
      legacyGenerateBlocked,
      handoffGateStrict,
      legacyAnalyzeDone,
      workshopStagesList,
      activeWorkshopStage?.handoffImportedAt,
      activeWorkshopStage?.workflowStatus,
      docTs,
      copyMddInicialMarkdown,
      handleHandoffGateStrictChange,
      resolveLegacyAnswerValue,
      setCentralPanel,
      fetchProject,
      legacyUpdateCodebaseDoc,
      legacySuggestBrdFromCodebaseDoc,
      legacyGenerateMdd,
      legacyGenerateDeliverables,
      legacyGenerateCodebaseDoc,
      legacyStart,
      legacyAnswer,
    ],
  );

  const workshopBenchmarkPanelProps = useMemo(
    (): import("./workshopBenchmarkPanel.types").WorkshopBenchmarkPanelProps => ({
      projectId,
      mergeAudit,
      dbgaContent,
      specContent,
      fase0Content,
      phase0IsEmpty,
      phase0EntryMode,
      benchmarkPhaseTab,
      benchmarkViewMode,
      phase0SummaryViewMode,
      benchmarkMarkdown,
      benchmarkNeedsRegenerate,
      phase0SummaryContent,
      loading,
      loadingReason,
      lastBenchmarkIdea,
      docTs,
      buildDocClarification,
      onBenchmarkPhaseTabChange: setBenchmarkPhaseTab,
      onPhase0Complete: handlePhase0Complete,
      onNavigatePanel: setCentralPanel,
      onDbgaRestoreOpen: () => setDbgaRestoreOpen(true),
      onDbgaContentChange: setDbgaContent,
      onPhase0SummaryContentChange: setPhase0SummaryContent,
      onBenchmarkBlur: handleBenchmarkBlur,
      onPhase0SummaryBlur: handlePhase0SummaryBlur,
      onSuggestBrdFromDbga: async () => {
        await suggestBrdFromDbga(projectId, { stageId: activeStageId ?? undefined });
      },
      onClearDbgaContent: clearDbgaContent,
      onClearPhase0SummaryContent: clearPhase0SummaryContent,
      onPhase0DeepResearch: phase0DeepResearch,
      onFetchProject: fetchProject,
    }),
    [
      projectId,
      mergeAudit,
      dbgaContent,
      specContent,
      fase0Content,
      phase0IsEmpty,
      phase0EntryMode,
      benchmarkPhaseTab,
      benchmarkViewMode,
      phase0SummaryViewMode,
      benchmarkMarkdown,
      benchmarkNeedsRegenerate,
      phase0SummaryContent,
      loading,
      loadingReason,
      lastBenchmarkIdea,
      docTs,
      buildDocClarification,
      handlePhase0Complete,
      setCentralPanel,
      setDbgaContent,
      setPhase0SummaryContent,
      handleBenchmarkBlur,
      handlePhase0SummaryBlur,
      suggestBrdFromDbga,
      activeStageId,
      clearDbgaContent,
      clearPhase0SummaryContent,
      phase0DeepResearch,
      fetchProject,
    ],
  );

const workshopMddPanelProps = useMemo(
    (): import("./workshopMddPanel.types").WorkshopMddPanelProps => ({
      projectId,
      activeStageId,
      mddContent,
      effectiveMddTrimmed,
      mddViewMode,
      mddDirty,
      mddReviewing,
      mddPersisting,
      mddReapplyingFormat,
      mddJustGeneratedFromBenchmark,
      loading,
      loadingReason,
      notice,
      isLegacyProject,
      isStage1Legacy,
      legacyMddNeedsCodebaseDoc,
      legacyHandoffGatePending,
      legacyChangeGateBlocked,
      legacyHandoffGateBlocked,
      legacyGenerateBlocked,
      handoffGateStrict,
      patternsWizardAnalyzing,
      canGenerate,
      cascadeRunning,
      cascadeCompleted,
      cascadeTotal,
      cascadePostPassRunning,
      buildDocClarification,
      isGenerationGateBlocked,
      onHandoffGateStrictChange: handleHandoffGateStrictChange,
      onClearMddJustGeneratedFromBenchmark: clearMddJustGeneratedFromBenchmark,
      onRequestGenerateMdd: requestGenerateMdd,
      onReapplyMddFormat: reapplyMddFormat,
      onOpenSuggestMddPatterns: openSuggestMddPatterns,
      onOpenEditMddPatterns: openEditMddPatterns,
      onOpenClearMddConfirm: () => setClearMddConfirmOpen(true),
      onGenerateDeliverables: handleGenerateDeliverables,
      onMddContentChange: setMddContent,
      onRevertMddContent: revertMddContent,
      onPersistAndReviewMdd: persistAndReviewMdd,
      onMddAuditUpdated: handleMddAuditUpdated,
    }),
    [
      projectId,
      activeStageId,
      mddContent,
      effectiveMddTrimmed,
      mddViewMode,
      mddDirty,
      mddReviewing,
      mddPersisting,
      mddReapplyingFormat,
      mddJustGeneratedFromBenchmark,
      loading,
      loadingReason,
      notice,
      isLegacyProject,
      isStage1Legacy,
      legacyMddNeedsCodebaseDoc,
      legacyHandoffGatePending,
      legacyChangeGateBlocked,
      legacyHandoffGateBlocked,
      legacyGenerateBlocked,
      handoffGateStrict,
      patternsWizardAnalyzing,
      canGenerate,
      cascadeRunning,
      cascadeCompleted,
      cascadeTotal,
      cascadePostPassRunning,
      buildDocClarification,
      isGenerationGateBlocked,
      handleHandoffGateStrictChange,
      clearMddJustGeneratedFromBenchmark,
      requestGenerateMdd,
      reapplyMddFormat,
      openSuggestMddPatterns,
      openEditMddPatterns,
      handleGenerateDeliverables,
      setMddContent,
      revertMddContent,
      persistAndReviewMdd,
      handleMddAuditUpdated,
    ],
  );

  const workshopSpecBrdAemPanelsProps = useMemo(
    (): import("./workshopSpecBrdAemPanels.types").WorkshopSpecBrdAemPanelsProps => ({
      centralPanel,
      projectId,
      activeStageId,
      effectiveMddTrimmed,
      dbgaContent,
      specContent,
      aemContent,
      uiScreensContent,
      brdWorkshopDraft,
      brdDocViewMode,
      specViewMode,
      aemViewMode,
      specDirty,
      aemDirty,
      brdWorkshopDirty,
      brdTobePersistBusy,
      loading,
      loadingReason,
      canGenerateFromCodebase,
      canGenerateAem,
      deliverablesReadOnly,
      clarifySpecDialogOpen,
      isLegacyProject,
      activeLegacyState,
      activeStageBrdContent: activeWorkshopStage?.brdContent,
      stageDeliverableView,
      docTs,
      buildDocClarification,
      onSpecContentChange: setSpecContent,
      onAemContentChange: setAemContent,
      onBrdWorkshopDraftChange: setBrdWorkshopDraft,
      onClarifySpecDialogOpenChange: setClarifySpecDialogOpen,
      onPersistSpecContent: () => void persistSpecContent(specContent ?? ""),
      onPersistAemContent: () => void persistAemContent(aemContent ?? ""),
      onPersistBrdWorkshopDraft: () => void persistBrdWorkshopDraft(),
      onGenerateSpec: () => generateSpec(projectId),
      onOpenAemGenerateDialog: () => setAemGenerateDialogOpen(true),
      onSyncUiScreens: () => void syncUiScreens(projectId),
      onSpecBlur: handleSpecBlur,
      onAemBlur: handleAemBlur,
      onFetchProject: fetchProject,
      onLegacyGenerateSpec: () =>
        void legacyGenerateFromCodebaseDoc(projectId, "spec", activeStageId ?? undefined),
      onLegacySuggestBrdFromCodebase: async () => {
        const res = await legacySuggestBrdFromCodebaseDoc(projectId, activeStageId ?? undefined);
        if (res?.brdContent) setBrdWorkshopDraft(res.brdContent);
      },
    }),
    [
      centralPanel,
      projectId,
      activeStageId,
      effectiveMddTrimmed,
      dbgaContent,
      specContent,
      aemContent,
      uiScreensContent,
      brdWorkshopDraft,
      brdDocViewMode,
      specViewMode,
      aemViewMode,
      specDirty,
      aemDirty,
      brdWorkshopDirty,
      brdTobePersistBusy,
      loading,
      loadingReason,
      canGenerateFromCodebase,
      canGenerateAem,
      deliverablesReadOnly,
      clarifySpecDialogOpen,
      isLegacyProject,
      activeLegacyState,
      activeWorkshopStage?.brdContent,
      stageDeliverableView,
      docTs,
      buildDocClarification,
      persistSpecContent,
      persistAemContent,
      persistBrdWorkshopDraft,
      generateSpec,
      syncUiScreens,
      handleSpecBlur,
      handleAemBlur,
      fetchProject,
      legacyGenerateFromCodebaseDoc,
      legacySuggestBrdFromCodebaseDoc,
    ],
  );

  const workshopAgentPanelsProps = useMemo(
    (): import("./workshopAgentPanels.types").WorkshopAgentPanelsProps => ({
      centralPanel,
      projectId,
      activeStageId,
      effectiveMddTrimmed,
      loading,
      loadingReason,
      agentGovernanceContent,
      agentGovernanceViewMode,
      agentGovernanceExportScaffold,
      agentGovernanceExportLoading,
      agentGovernanceGenerating,
      hasAgentGovernance,
      documentationGapsRefreshNonce,
      onGenerateAgentGovernance: () => generateAgentGovernance(projectId),
      onFetchProject: fetchProject,
    }),
    [
      centralPanel,
      projectId,
      activeStageId,
      effectiveMddTrimmed,
      loading,
      loadingReason,
      agentGovernanceContent,
      agentGovernanceViewMode,
      agentGovernanceExportScaffold,
      agentGovernanceExportLoading,
      agentGovernanceGenerating,
      hasAgentGovernance,
      documentationGapsRefreshNonce,
      generateAgentGovernance,
      fetchProject,
    ],
  );

  const workshopUxGuidePanelProps = useMemo(
    (): import("./workshopUxGuidePanel.types").WorkshopUxGuidePanelProps => ({
      projectName,
      uxUiGuideContent,
      uxUiGuideDirty,
      uxUiGuideViewMode,
      effectiveMddTrimmed,
      blueprintContent,
      loading,
      uxGenerating,
      uxGuideDesignRef: project?.uxGuideDesignRef ?? "auto",
      docTs,
      onUxUiGuideContentChange: setUxUiGuideContent,
      onPersistUxUiGuideContent: persistUxUiGuideContent,
      onGenerateUxGuide: generateUxGuideSequential,
      onDesignRefChange: handleDesignRefChange,
      onUxUiGuideBlur: handleUxUiGuideBlur,
    }),
    [
      projectName,
      uxUiGuideContent,
      uxUiGuideDirty,
      uxUiGuideViewMode,
      effectiveMddTrimmed,
      blueprintContent,
      loading,
      uxGenerating,
      project?.uxGuideDesignRef,
      docTs,
      persistUxUiGuideContent,
      generateUxGuideSequential,
      handleDesignRefChange,
      handleUxUiGuideBlur,
    ],
  );

  const workshopAdrsPluginPanelsProps = useMemo(
    (): import("./workshopAdrsPluginPanels.types").WorkshopAdrsPluginPanelsProps => ({
      centralPanel,
      projectId,
      activeStageId,
      adrs,
      pluginArtifactTypes,
      onRefreshAdrs: fetchAdrs,
    }),
    [centralPanel, projectId, activeStageId, adrs, pluginArtifactTypes, fetchAdrs],
  );


  return {
    centralPanel,
    legacy: workshopLegacyPanelsProps,
    benchmark: workshopBenchmarkPanelProps,
    mdd: workshopMddPanelProps,
    standard: workshopStandardDocPanelsProps,
    ux: workshopUxGuidePanelProps,
    specBrdAem: workshopSpecBrdAemPanelsProps,
    agent: workshopAgentPanelsProps,
    adrsPlugin: workshopAdrsPluginPanelsProps,
  };
}
