/**
 * Injection tokens for circular dependency chains.
 * Using string tokens instead of class references in @Inject() breaks
 * ESM TDZ cycles because the token file has no class imports.
 */
export const PROJECTS_SERVICE_TOKEN = 'PROJECTS_SERVICE';
export const PROJECT_INTEGRATION_SERVICE_TOKEN = 'PROJECT_INTEGRATION_SERVICE';
export const LEGACY_COORDINATOR_SERVICE_TOKEN = 'LEGACY_COORDINATOR_SERVICE';
export const DOCUMENTATION_GAP_SERVICE_TOKEN = 'DOCUMENTATION_GAP_SERVICE';
export const RESOLVE_CHANGE_TO_FILES_SERVICE_TOKEN = 'RESOLVE_CHANGE_TO_FILES_SERVICE';
export const DOC_RECONCILE_SERVICE_TOKEN = 'DOC_RECONCILE_SERVICE';
export const DELIVERABLES_QUEUE_SERVICE_TOKEN = 'DELIVERABLES_QUEUE_SERVICE';
export const PROJECT_GENERATION_GUARD_SERVICE_TOKEN = 'PROJECT_GENERATION_GUARD_SERVICE';
