/**
 * Spec-Kit Bundle v2 — incluye types.json, operations.json y .cursorrules
 * en la exportación ZIP para que Cursor/Claude tengan specs estructuradas.
 */

import {
  SpecKitBundleFile,
  SpecKitBundleInput,
  specKitFeatureDir,
  extractMddSection,
} from "@theforge/shared-types";

/**
 * Genera .cursorrules desde MDD §2 (Arquitectura y Stack).
 * Instrucciones de estilo para el agente implementador.
 */
function generateCursorRules(mdd: string): string {
  const s2 = extractMddSection(mdd, 2);
  const stack = extractStackFromSection2(s2);

  return `# .cursorrules — Generated by TheForge
# Stack detectado: ${stack.join(", ")}

# 🎯 Reglas de implementación (auto-generadas desde MDD §2)

## Stack técnico
${stack.map((s) => `- ${s}`).join("\n")}

## Reglas de código
- Usa TypeScript estricto (strict: true en tsconfig).
- Prefiere interfaces sobre types para shapes de datos.
- Usa Zod para validación de inputs (NO class-validator).
- Backend: NestJS con Prisma. Un servicio por entidad.
- Frontend: React + Vite + Tailwind. Hooks con TanStack Query.
- Forms: react-hook-form + zodResolver.
- Tests: Jest (unit) + Playwright (e2e).

## Patrones de inferencia aplicados
- Si ves <code-deletedAt> en un modelo, usa soft-delete (UPDATE set deletedAt).
- Si ves <code-createdAt>, considera la entidad auditable.
- Todos los endpoints LIST usan cursor pagination (pageSize=20).
- Todos los POST/PATCH/DELETE requieren verificación de auth.
- Si el MDD indica roles, usa @Roles() o @SelfOrAdmin() en controllers.

## Testing obligatorio
- Cada endpoint público DEBE tener test e2e.
- Cada función pura (utils, services) DEBE tener test unitario.
- Coverage mínimo: 80% branches.

## Git workflow
- Usa la rama del stage: \`{NNN}-{slug}\`.
- Commits en inglés, formato: \`feat(scope): description\`.
- No commitear .env ni secrets.
`;
}

function extractStackFromSection2(s2: string): string[] {
  const stack: string[] = [];
  const keywords = [
    { name: "NestJS", pattern: /nestjs/i },
    { name: "React", pattern: /react(?!-native)/i },
    { name: "Vite", pattern: /vite/i },
    { name: "Tailwind CSS", pattern: /tailwind/i },
    { name: "Prisma", pattern: /prisma/i },
    { name: "PostgreSQL", pattern: /postgres|postgresql/i },
    { name: "TypeScript", pattern: /typescript|ts\b/i },
    { name: "Docker", pattern: /docker/i },
    { name: "Traefik", pattern: /traefik/i },
    { name: "BullMQ", pattern: /bullmq|bull/i },
    { name: "Redis", pattern: /redis/i },
    { name: "LangGraph", pattern: /langgraph/i },
    { name: "OpenRouter", pattern: /openrouter/i },
    { name: "FalkorDB", pattern: /falkor/i },
    { name: "Next.js", pattern: /next\.?js/i },
  ];

  for (const { name, pattern } of keywords) {
    if (pattern.test(s2)) stack.push(name);
  }

  return stack;
}

/**
 * Extiende SpecKitBundleInput para v2.
 */
export interface SpecKitBundleInputV2 extends SpecKitBundleInput {
  typesJsonContent?: string | null;
  operationsJsonContent?: string | null;
  tasksJsonContent?: string | null;
  inferenceRulesContent?: string | null;
  leanSdd?: boolean;
}

/**
 * Genera los archivos del spec-kit v2.
 * Backwards-compatible con v1 (todos los campos legacy se mantienen).
 */
export function buildSpecKitBundleFilesV2(input: SpecKitBundleInputV2): SpecKitBundleFile[] {
  // Obtener bundle base v1
  const { buildSpecKitBundleFiles } = require("@theforge/shared-types");
  const baseFiles: SpecKitBundleFile[] = buildSpecKitBundleFiles(input);

  const featureDir = specKitFeatureDir(input.featureOrdinal ?? 1, input.projectName);
  const v2Files: SpecKitBundleFile[] = [];

  // Derivados estructurados
  const typesJson = (input.typesJsonContent ?? "").trim();
  if (typesJson) {
    v2Files.push({
      path: `${featureDir}/types.json`,
      content: typesJson,
    });
  }

  const operationsJson = (input.operationsJsonContent ?? "").trim();
  if (operationsJson) {
    v2Files.push({
      path: `${featureDir}/operations.json`,
      content: operationsJson,
    });
  }

  const tasksJson = (input.tasksJsonContent ?? "").trim();
  if (tasksJson) {
    v2Files.push({
      path: `${featureDir}/tasks.json`,
      content: tasksJson,
    });
  }

  const inferenceRules = (input.inferenceRulesContent ?? "").trim();
  if (inferenceRules) {
    v2Files.push({
      path: `${featureDir}/inference-rules.yaml`,
      content: inferenceRules,
    });
  }

  // .cursorrules para el agente implementador
  const mdd = (input.mddContent ?? "").trim();
  if (mdd) {
    v2Files.push({
      path: ".cursorrules",
      content: generateCursorRules(mdd),
    });
  }

  // Quickstart v2 (enriched)
  const quickstart = buildQuickstartV2(input);
  if (quickstart) {
    v2Files.push({
      path: `${featureDir}/quickstart.md`,
      content: quickstart,
    });
  }

  // Fusión: v2 files tienen prioridad (sobrescriben si path duplicado)
  const merged = new Map<string, SpecKitBundleFile>();
  for (const f of baseFiles) merged.set(f.path, f);
  for (const f of v2Files) merged.set(f.path, f); // v2 gana

  return [...merged.values()];
}

/**
 * Quickstart mejorado que usa operations.json en lugar de heurísticas regex.
 */
function buildQuickstartV2(input: SpecKitBundleInputV2): string {
  const lines: string[] = ["# Quickstart v2", ""];

  const mdd = (input.mddContent ?? "").trim();

  // Detectar package manager desde operations.json si existe
  let pm = "pnpm";
  try {
    const ops = input.operationsJsonContent ? JSON.parse(input.operationsJsonContent) : null;
    if (ops?.inferenceSettings?.defaults?.packageManager) {
      pm = ops.inferenceSettings.defaults.packageManager;
    }
  } catch {
    // fallback a regex legacy
    const section2 = extractMddSection(mdd, 2);
    if (/\byarn\b/i.test(section2)) pm = "yarn";
    if (/\bnpm\b/i.test(section2) && !/\bpnpm\b/i.test(section2)) pm = "npm";
  }

  lines.push("## Arranque local", "");
  lines.push(`- Instalar dependencias: \`${pm} install\``);
  lines.push("- Generar Prisma client: \`npx prisma generate\`");

  try {
    const ops = input.operationsJsonContent ? JSON.parse(input.operationsJsonContent) : null;
    if (ops?.globalFeatures?.softDelete?.enabled) {
      lines.push("- ⚠️ Soft-delete activo: recuerda filtrar `deletedAt: null` en queries");
    }
  } catch {
    // ignore
  }

  if (/docker\s+compose|docker-compose/i.test(mdd)) {
    lines.push("- Levantar servicios: \`docker compose up -d\`");
  }

  const devScript = mdd.match(/(?:pnpm|npm|yarn)\s+(?:run\s+)?(?:dev|start:dev)\b/i)?.[0];
  if (devScript) lines.push(`- Arrancar app: \`${devScript.trim()}\``);

  lines.push("", "## Seed / Datos de prueba", "");
  lines.push("- \`npx prisma db seed\` (si hay seed.ts)");

  lines.push("", "## Tests", "");
  lines.push("- Unitarios: \`npm test\`");
  lines.push("- E2E: \`npm run test:e2e\`");
  lines.push("- Watch: \`npm run test:watch\`");

  lines.push("", "## Estructura de especificaciones (v2)", "");
  lines.push("| Archivo | Propósito |");
  lines.push("|---|---|");
  lines.push("| \`types.json\` | Esquemas Zod + tipos TypeScript derivados del MDD §3 |");
  lines.push("| \`operations.json\` | CRUD, endpoints, auth, frontend por entidad |");
  lines.push("| \`tasks.json\` | Tasks ejecutables con código esperado y verificación |");
  lines.push("| \`inference-rules.yaml\` | Reglas de inferencia aplicadas (CRUD auto, etc.) |");
  lines.push("| \`.cursorrules\` | Reglas de estilo para el agente implementador |");

  return lines.join("\n");
}

// Export backwards-compatible

